name: Integration
"on":
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Install required tools
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker

      - name: Run unit tests
        run: |
          dotnet test --configuration Release --collect:"XPlat Code Coverage"

      - name: Generate report
        run: |
          reportgenerator \
            -reports:"**/TestResults/*/coverage.cobertura.xml" \
            -targetdir:"coverage-report" \
            -reporttypes:Html

      - name: Run Mutation Tests
        working-directory: ./server/Tests
        run: |
          dotnet stryker --break-at 80 --reporter html

      - name: Collect Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./server/coverage-report
          if-no-files-found: 'warn'

      - name: Collect Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-report
          path: ./server/Tests/StrykerOutput
          if-no-files-found: 'warn'
    